name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.17.1 ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 16.17.1 
        cache: 'npm'
    - name: Install server dependencies
      run: |
        cd server
        npm install --prefer-offline --no-audit --no-optional --no-fund --no-save --no-save-dev --no-progress --loglevel=error
    - name: Build server
      run: |
        cd server
        npm i
        npm run test &
        sleep 10
      
    - name: Build client 
      run: | 
        cd client
        npm i
        npm run build
